name: Automated News Scraping

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Discover news URLs from RSS feeds
      id: discover
      timeout-minutes: 10
      run: |
        timeout 600 python discovery_engine.py || echo "Discovery timeout, using available URLs"
        # Get first 30 URLs for this run - more comprehensive scraping  
        if [ -f discovered_urls.txt ]; then
          URLS=$(head -30 discovered_urls.txt | tr '\n' ',' | sed 's/,$//')
          echo "urls=$URLS" >> $GITHUB_OUTPUT
          echo "Found $(wc -l < discovered_urls.txt) total URLs, using first 30"
          echo "Sources: CNN, Guardian, Reuters, BBC, NPR, TechCrunch, NY Times, Washington Post, NBC, CBS, ABC, Sky News, Al Jazeera"
        else
          echo "No URLs discovered, will skip scraping"
          echo "urls=" >> $GITHUB_OUTPUT
        fi
        
    - name: Run news scraper
      timeout-minutes: 15
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        if [ -n "${{ steps.discover.outputs.urls }}" ]; then
          cd news_scraper
          timeout 900 scrapy crawl news_spider -a urls="${{ steps.discover.outputs.urls }}" || echo "Scraper timeout"
        else
          echo "No URLs to scrape, skipping"
        fi
        
    - name: Check scraping results
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python check_articles.py
        
    - name: Upload logs as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraping-logs-${{ github.run_number }}
        path: |
          news_scraper/scrapy_log.txt
          discovered_urls.txt
        retention-days: 7
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "News scraping workflow failed!"
        echo "Check the logs for details."
        # Could add email notification here